title: Musashi's Blog
email: rohith.narsing@gmail.com
description: >-
    Notes on computer architecture,
    digital design and Linux.
baseurl: "" 
url: "https://rohith-04.github.io/" 
github_username:  Rohith-04

# Build settings
theme: minima
plugins:
  - jekyll-feed
